name: Deploy Gondia Today

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, gondia-server]

    steps:
      - name: Update production folder
        shell: powershell
        run: |
          cd C:\gondia\gondia-share
          git pull origin main

      - name: Stop live website
        shell: powershell
        run: |
          & "C:\Users\Administrator\AppData\Roaming\npm\pm2.cmd" stop gondiatoday-web

      - name: Install dependencies
        shell: powershell
        run: |
          cd C:\gondia\gondia-share
          npm ci

      - name: Generate Prisma Client
        shell: powershell
        run: |
          cd C:\gondia\gondia-share
          npx prisma generate

      - name: Build the website
        shell: powershell
        run: |
          cd C:\gondia\gondia-share
          npm run build

      - name: Restart the live website
        shell: powershell
        run: |
          & "C:\Users\Administrator\AppData\Roaming\npm\pm2.cmd" restart gondiatoday-web